export const urlBase = "https://newguajalotas.onrender.com/"
export const urlComida = "https://newguajalotas.onrender.com/comidas"
export const urlUsuario = "https://newguajalotas.onrender.com/usuarios" 
export const urlCarritos = "https://newguajalotas.onrender.com/carts"
export const urlCopias = "https://newguajalotas.onrender.com/discount"